### ISSUE TITLE
Formatting issue with nested IF/THEN

### ISSUE THREAD

**Issue by MikeGlue** [RasmusTidselbak/al-formatter#1]
Seems to be an issue when there are embed IF / THEN statements.

Example:
![image](https://user-images.githubusercontent.com/5204734/31247598-158f0fd4-a9df-11e7-9664-9802a50974c8.png)

After formatting, the last END is moved to the wrong position:
![image](https://user-images.githubusercontent.com/5204734/31247480-bd24b024-a9de-11e7-8fd3-3c0aaa7c834b.png)

**Comment by RasmusTidselbak** [comment]
Hi Mike,
Thank you for the information. 
I've got a new version in beta right now, which solves the issue.

**Comment by RasmusTidselbak** [comment]
It has been solved in the current release, thanks for helping me :)
