### ISSUE TITLE
Issue with case

### ISSUE THREAD

**Issue by salmosa1** [RasmusTidselbak/al-formatter#10]
Hi,
I'm having an issue when formatting a case.
This code
![image](https://user-images.githubusercontent.com/37341780/37352490-a5d7e89c-26dd-11e8-859b-9f24b817adca.png)
is transformed to 
![image](https://user-images.githubusercontent.com/37341780/37352512-ae686eaa-26dd-11e8-8d03-5930fbdedd14.png)

It throws an error,
![image](https://user-images.githubusercontent.com/37341780/37352557-cdb9975c-26dd-11e8-8981-d07fb20a0d42.png)

I don't know if I'm doing something wrong or if it is a bug,

Thanks!

**Comment by RasmusTidselbak** [comment]
I'll look into it, thank you for notifying me 👍
