### ISSUE TITLE
Space after ,

### ISSUE THREAD

**Issue by Dreckiger-Dan** [RasmusTidselbak/al-formatter#12]
The [AL best practice](https://docs.microsoft.com/de-de/dynamics365/business-central/dev-itpro/compliance/apptest-bestpracticesforalcode#example-3) says, you should call a method with multiple parameters like this:
`MyFunction(Param1, Param2);`
The formatter formats it to:
`MyFunction(Param1,Param2);`

Installed Version: 2.1.0

**Comment by RasmusTidselbak** [comment]
Thanks for notifying me :)
