### ISSUE TITLE
Doesn't seem to be working for me

### ISSUE THREAD

**Issue by BartPermentier** [RasmusTidselbak/al-formatter#16]
Am i missing anything?
![image](https://user-images.githubusercontent.com/24684493/50639912-77f16b00-0f63-11e9-8a98-03b12cc85df4.png)

**Comment by RasmusTidselbak** [comment]
There is a conflict between Microsoft AL Language and AL Formatter, so the AL Formatter is allowing AL Language to do all formatting. Which means that AL Formatter basically does nothing.

**Comment by BartPermentier** [comment]
Oh to bad, yours seemed better :(
I tried loading an old vsix but it also did not work.

Thanks for the reply!

**Comment by RasmusTidselbak** [comment]
FYI: I've included some of the features in my other Extension AL Variable Helper.
Specifically Sorting variables and fixing casing.

**Comment by BartPermentier** [comment]
Just tested it and it works. Thanks a lot! :)
