### ISSUE TITLE
TableRelation = too much indention

### ISSUE THREAD

**Issue by epernst** [RasmusTidselbak/al-formatter#2]
Love this little extension, using it with a TableRelation with if's and where on different lines cause the following lines to indent.

![31fd70f7-17bf-4f38-a9e8-b8f1b7cf6a30](https://user-images.githubusercontent.com/5236163/32348062-eddd2742-c012-11e7-8ea5-d90c7c96719c.GIF)

Also CONST + FILTER is not changed to lower case.

**Comment by RasmusTidselbak** [comment]
I'm looking into it, thanks for notifying.

**Comment by RasmusTidselbak** [comment]
@epernst I'll put a new version up tomorrow, which solves both this issue and #3 .
Thanks again for helping me out :)

**Comment by epernst** [comment]
Has not been fixed. In fact it seems it has gotten worse. 
Try to run it with this code:
`trigger OnValidate();
begin
if true = false then
Status := 1;

if true and
(Status = 2)
then begin
Status := 3
end else
if true and
(Status = 2)
else
if true and
(Status = 2) then
Status := 3
end;
`
