### ISSUE TITLE
Multi-line procedural var declarations: Too much indention

### ISSUE THREAD

**Issue by epernst** [RasmusTidselbak/al-formatter#3]
The old pascal developer in me really like how procedure declarations now is almost like in pascal.
That means we can split the declaration lines and make the code even more readable, even with lots of vars.
But right now if that's used, then it cases the following lines to be too much indented.

![7f7d9a65-10ee-4292-9fe9-7200c379e694](https://user-images.githubusercontent.com/5236163/32349116-508a5038-c016-11e7-85b8-734ec81be5f6.GIF)

**Comment by RasmusTidselbak** [comment]
I'll look into it.

**Comment by epernst** [comment]
This issue also remains in 2.1.0. Are you sure that you uploaded the new version?
