### ISSUE TITLE
'x''x' becomes 'x' 'x'

### ISSUE THREAD

**Issue by epernst** [RasmusTidselbak/al-formatter#4]
If you have a string like **'x''x'** then when formatting it becomes **'x' 'x'**.
The extra space causes the compiler to complain with a "',' expected" message.

**Comment by RasmusTidselbak** [comment]
Do you have an example on the issue?

**Comment by epernst** [comment]
String := '''*' + String2 + '*''';

**Comment by epernst** [comment]
Well markup removes the "star" - but if x was a "star" then: String := '''x' + String2 + 'x''';

**Comment by RasmusTidselbak** [comment]
I've got it now, the next release fixes the issue :)

**Comment by epernst** [comment]
If this is supposed to have been fixed in 2.1.0, then I'm sorry but the problem is still there.
