### ISSUE TITLE
'' becomes ' '

### ISSUE THREAD

**Issue by waldo1001** [RasmusTidselbak/al-formatter#6]
Which makes the text 

Message('let''s show a message');

to 

Message('let' 's show a message');

which doesn't compile

**Comment by RasmusTidselbak** [comment]
Are you on version 2.1.0, which was released on sunday?
I've fixed a similar issue in that versioner.

**Comment by waldo1001** [comment]
I am:
![image](https://user-images.githubusercontent.com/12088142/32512587-d328a1a4-c3f7-11e7-82f8-ce4d230c32c1.png)

**Comment by RasmusTidselbak** [comment]
All right, I'll look into it.

**Comment by RasmusTidselbak** [comment]
The issue is, that I try to isolate keywords, strings and types through regular expressions.
I think that I've managed to allow my expression to include double ' in strings.

I'll do some testing and hopefully I can have it ready in the next couple of days.
