### ISSUE TITLE
Error: Cannot read property 'trim' of undefined   Code: -32603

### ISSUE THREAD

**Issue by zzhangCLPA** [RasmusTidselbak/al-formatter#9]
when i format an AL document, i get error:
[Error - 9:35:10 AM] Request textDocument/formatting failed.
  Message: Request textDocument/formatting failed with message: Cannot read property 'trim' of undefined
  Code: -32603 

i use V2.1.0

**Comment by RasmusTidselbak** [comment]
Do you know which piece of code is causing the error?

**Comment by zzhangCLPA** [comment]
when i format the document i get the error. i attached the document to hope you can find why.
[ClpaSetup.zip](https://github.com/RasmusTidselbak/al-formatter/files/1673671/ClpaSetup.zip)
